name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web --web-renderer canvaskit --release --base-href /

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          cname: vstupenka.online